services:
  nginx:
    image: nginx:latest
    container_name: portal
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/home_listings:/usr/share/nginx/html
    
  postgres:
    image: postgres:latest
    container_name: backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techbleat
    volumes:
      - /home/ec2-user/data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:latest
    container_name: prom-cont
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ec2-user/prom-data:/etc/prometheus
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: graf-cont
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: lancer
      GF_SECURITY_ADMIN_PASSWORD: lancer
    restart: always
volumes:
  data:
  
